server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: authuser
    password: authpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    # Show SQL for debugging during development
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

security:
  jwt:
    secret-key: mysupersecretkeyformicroservicesauthenticationandjwttokens2024
    expiration-time: 3600000  # 1 hour in milliseconds
    token-prefix: "Bearer "
    header-name: "Authorization" 